### ISSUE TITLE
Not able to download VM.

### ISSUE THREAD

**Issue by kumarkshiv** [nsg-ethz/Blink#1]
I am a research student and I am working on anomaly detection. I wanted to explore BLINK and I was not able to download the VM.
Could you please help me download the VM.?

I am getting the below error.

![image](https://user-images.githubusercontent.com/13508717/131703759-971be32a-4690-4e40-921a-b64979125ce5.png)

**Comment by KTrel** [comment]
Hello @shivkumar301 and sorry for my late reply. 
We are currently building a better VM, which will provide an upgraded p4-utils version and python3 support. This is why the link is temporarily broken. As soon as the new VM is ready (we hope next week), we will upload it and I will update the link in this repo.

**Comment by kumarkshiv** [comment]
Thank you for the reply.

**Comment by KTrel** [comment]
Hi,

I have uploaded a working VM and updated the link in the repo. 

Have a good day,
Thomas
